# Generated by Django 2.2 on 2019-04-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=' ', max_length=200)),
                ('content', models.CharField(default=' ', max_length=1000)),
            ],
        ),
    ]
